name: Dockerized CI Pipeline

on: [push] # Chạy mỗi khi push code

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Mượn máy chủ Linux của GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-test-image . 
        # Lệnh này yêu cầu GitHub tự build Docker image từ file Dockerfile

      - name: Run Tests inside Docker
        run: docker run my-test-image
        # Lệnh này chạy container và kích hoạt pytest